### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MCArth** [1Euro7Cent/cooldown#1]
Hi, I see this module never removes ids from the this.users list, which causes the length of the list to only ever grow. I think this could be avoided by removing users from the list when they haven't sent a message for a certain amount of time.

**Comment by 1Euro7Cent** [comment]
Thx for that info. I never thought of that. Ill fix that when im at my pc

**Comment by 1Euro7Cent** [comment]
This should be fixed. If you don't think so please reopen this issue.
